// Writes unicode.lang: the Unicode categories gron needs, as range tables
// taken from Go's unicode package (so the port matches the Go version).
// Run: go run . > ../../unicode.lang
package main

import (
	"fmt"
	"strings"
	"unicode"
)

func ranges(tabs ...*unicode.RangeTable) [][2]rune {
	var out [][2]rune
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if !unicode.In(r, tabs...) {
			continue
		}
		if n := len(out); n > 0 && out[n-1][1] == r-1 {
			out[n-1][1] = r
		} else {
			out = append(out, [2]rune{r, r})
		}
	}
	return out
}

func emit(name, doc string, rs [][2]rune) {
	fmt.Printf("// %s\n// Pairs of first and last code points, sorted.\nlet %s = [\n", doc, name)
	var line []string
	for _, r := range rs {
		line = append(line, fmt.Sprintf("0x%X, 0x%X", r[0], r[1]))
		if len(line) == 6 {
			fmt.Printf("  %s,\n", strings.Join(line, ", "))
			line = nil
		}
	}
	if len(line) > 0 {
		fmt.Printf("  %s,\n", strings.Join(line, ", "))
	}
	fmt.Printf("]\n\n")
}

func main() {
	fmt.Printf("// Unicode categories, generated by scripts/genunicode from Go's unicode\n")
	fmt.Printf("// package (Unicode %s). Do not edit.\n//\n", unicode.Version)
	fmt.Printf("// lang's String.is_letter is not the Unicode letter category (it is true\n")
	fmt.Printf("// for digits like U+0661 and marks like U+0301, false for U+216B), and\n")
	fmt.Printf("// there is no other way to ask for a category.\n\n")
	emit("first_ranges", "Lu, Ll, Lm, Lo, Nl: what may start an identifier", ranges(unicode.Lu, unicode.Ll, unicode.Lm, unicode.Lo, unicode.Nl))
	emit("secondary_ranges", "Mn, Mc, Nd, Pc: what may also follow the first character", ranges(unicode.Mn, unicode.Mc, unicode.Nd, unicode.Pc))
	emit("number_ranges", "Nd, Nl, No: unicode.IsNumber", ranges(unicode.Nd, unicode.Nl, unicode.No))
	fmt.Print(`// Whether the code point r is in a table of ranges (binary search).
fn in_ranges(table: List<Int>, r: Int) -> Bool {
  var lo = 0
  var hi = table.length.div(2)
  while lo < hi {
    let mid = (lo + hi).div(2)
    if r < table[mid * 2] {
      hi = mid
    } else if r > table[mid * 2 + 1] {
      lo = mid + 1
    } else {
      return true
    }
  }
  return false
}

// Go's unicode.In(r, Lu, Ll, Lm, Lo, Nl)
pub fn is_first(r: Int) -> Bool {
  return in_ranges(first_ranges, r: r)
}

// Go's unicode.In(r, Mn, Mc, Nd, Pc)
pub fn is_secondary(r: Int) -> Bool {
  return in_ranges(secondary_ranges, r: r)
}

// Go's unicode.IsNumber
pub fn is_number(r: Int) -> Bool {
  return in_ranges(number_ranges, r: r)
}

test "categories" {
  expect is_first(0x61)
  expect is_first(0xE9)
  expect is_first(0x216B)
  expect not is_first(0x661)
  expect not is_first(0x1C5)
  expect is_secondary(0x661)
  expect is_secondary(0x301)
  expect is_secondary(0x203F)
  expect not is_secondary(0x61)
  expect is_number(0x39)
  expect is_number(0xBD)
  expect not is_number(0x41)
}
`)
}
