#!/usr/bin/env python3
"""Writes compiler/src/runtime/unicode.h: Unicode category and case tables
for String.is_letter / is_upper / is_lower / lower / upper, from Python's
unicodedata."""
import os
import sys
import unicodedata


def ranges(pred):
    out, start = [], None
    for c in range(0x110000):
        ok = pred(unicodedata.category(chr(c)))
        if ok and start is None:
            start = c
        if not ok and start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, rs):
    lines = [f"static const uint32_t {name}[][2] = {{"]
    row = []
    for a, b in rs:
        row.append(f"{{0x{a:X}, 0x{b:X}}}")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def pairs(name, f):
    ps = []
    for c in range(0x80, 0x110000):
        m = f(chr(c))
        if len(m) == 1 and m != chr(c):
            ps.append((c, ord(m)))
    lines = [f"static const uint32_t {name}[][2] = {{"]
    row = []
    for a, b in ps:
        row.append(f"{{0x{a:X}, 0x{b:X}}}")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


out = [
    f"// Unicode {unicodedata.unidata_version} categories, generated by tools/gen_unicode.py. Do not edit.",
    "// Sorted ranges of code points (first, last).",
    "",
    "// L: letters (Lu, Ll, Lt, Lm, Lo)",
    table("lt_uc_letter", ranges(lambda c: c.startswith("L"))),
    "// Lu",
    table("lt_uc_upper", ranges(lambda c: c == "Lu")),
    "// Ll",
    table("lt_uc_lower", ranges(lambda c: c == "Ll")),
    "// Case mappings past ASCII, one character to one (code point, mapped)",
    pairs("lt_uc_to_lower", str.lower),
    pairs("lt_uc_to_upper", str.upper),
    "",
]
path = os.path.join(os.path.dirname(__file__), "..", "compiler", "src", "runtime", "unicode.h")
open(path, "w").write("\n".join(out))
print(path, file=sys.stderr)
